apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: qdrant-cluster
  labels:
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
        app.kubernetes.io/name: qdrant
        app.kubernetes.io/instance: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
          - containerPort: 6333
        env:
          - name: QDRANT__SERVICE__SHARD_NUMBER
            value: "6"
        volumeMounts:
          - name: qdrant-storage
            mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-data
