apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3-eu
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer