# Qdrant Cluster Switzerland Region Configuration
replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: "v1.7.4"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  httpPort: 6333
  grpcPort: 6334
  p2pPort: 6335
  httpNodePort: 31333
  grpcNodePort: 31334
  p2pNodePort: 31335

# Namespace configuration
namespace: qdrant-cluster

persistence:
  enabled: true
  storageClass: "ebs-gp3-eu"
  size: 50Gi
  accessMode: ReadWriteOnce


# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi


# Pod disruption budget
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1


affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - qdrant-eu
        topologyKey: kubernetes.io/hostname


config:
  cluster:
    enabled: true
    node_id: "eu-cluster-worker-1"
    p2p:
      port: 6335
      bootstrap:
        - "qdrant-ap-0.qdrant-ap-headless.qdrant-cluster.svc.cluster.local:6335"
        - "qdrant-ap-1.qdrant-ap-headless.qdrant-cluster.svc.cluster.local:6335"
        - "qdrant-ap-2.qdrant-ap-headless.qdrant-cluster.svc.cluster.local:6335"
  service:
    api_key: "switzerland-cluster-api-key"
    read_only_api_key: "switzerland-cluster-read-only-api-key"
    http_port: 6333
    grpc_port: 6334
  storage:
    storage_path: "/qdrant/storage"
    snapshots_path: "/qdrant/snapshots"
    on_disk_payload: true
  log_level: "INFO"


env:
  - name: QDRANT__CLUSTER__ENABLED
    value: "true"
  - name: QDRANT__CLUSTER__P2P__PORT
    value: "6335"
  - name: QDRANT__CLUSTER__NODE_ID
    value: "eu-cluster-worker-1"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

nodeSelector:
  topology.kubernetes.io/region: eu-central-1

tolerations: []