replicaCount: 3

image:
  repository: qdrant/qdrant
  tag: "v1.7.4"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  httpPort: 6333
  grpcPort: 6334
  p2pPort: 6335
  httpNodePort: 30333
  grpcNodePort: 30334
  p2pNodePort: 30335

namespace: qdrant-cluster

persistence:
  enabled: true
  storageClass: "gp3-ssd-ap"
  size: 50Gi
  accessMode: ReadWriteOnce

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - qdrant-ap
        topologyKey: kubernetes.io/hostname

config:
  cluster:
    enabled: true
    node_id: "ap-master-node"
    p2p:
      port: 6335
  service:
    api_key: "cross-region-cluster-api-key"
    read_only_api_key: "cross-region-read-only-key"
    http_port: 6333
    grpc_port: 6334
  storage:
    storage_path: "/qdrant/storage"
    snapshots_path: "/qdrant/snapshots"
    on_disk_payload: true
  log_level: "INFO"

env:
  - name: QDRANT__CLUSTER__ENABLED
    value: "true"
  - name: QDRANT__CLUSTER__P2P__PORT
    value: "6335"
  - name: QDRANT__CLUSTER__NODE_ID
    value: "ap-master-node"
  - name: QDRANT__SERVICE__HOST
    value: "0.0.0.0"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

nodeSelector:
  topology.kubernetes.io/region: ap-south-1

tolerations: []

labels:
  region: ap-south-1
  cluster-role: master