apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3-eu
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.aws.com/zone
    values:
    - eu-central-1a
    - eu-central-1c
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete