# Qdrant Cluster Switzerland Region Configuration
replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  httpPort: 6333
  grpcPort: 6334
  httpNodePort: 30333
  grpcNodePort: 30334

persistence:
  enabled: true
  storageClass: "gp3-ssd"
  size: 50Gi
  accessMode: ReadWriteOnce


resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi


# Pod disruption budget
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1


affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - qdrant
        topologyKey: kubernetes.io/hostname


config:
  cluster:
    enabled: true
    node_id: "switzerland-cluster"
    p2p:
      port: 6335
    consensus:
      max_message_queue_size: 16384
  service:
    api_key: "switzerland-cluster-api-key"
    read_only_api_key: "switzerland-cluster-read-only-api-key"
    http_port: 6333
    grpc_port: 6334
  storage:
    storage_path: "/qdrant/storage"
    snapshots_path: "/qdrant/snapshots"
    on_disk_payload: true
  log_level: "INFO"


env:
  - name: QDRANT__CLUSTER__ENABLED
    value: "true"
  - name: QDRANT__CLUSTER__NODE_ID
    value: "switzerland-shard"
  - name: QDRANT__CLUSTER__P2P__PORT
    value: "6335"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

nodeSelector:
  region: switzerland

tolerations: []