apiVersion: v1
kind: Service
metadata:
  name: qdrant-loadbalancer
  namespace: qdrant-cluster
spec:
  type: LoadBalancer
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334